// =================================================================
// 강사 데이터 — page.js 및 teachers/[id]/page.js 공유
// =================================================================

export const INSTRUCTORS = [
  {
    id: 'gang-yeol-hyeok',
    name: '강열혁',
    role: '원장',
    instrument: '플루트',
    icon: '🎶',
    part: '관현악',
    education: ['연세대학교 음악대학원 졸업 (플루트 전공)'],
    career: [
      'JNC 음악학원 설립 · 운영 (2013~현재)',
      '플루트 독주회 다수 개최',
      '목동 지역 음악교육 발전 기여',
    ],
    bio: '연세대학교 음악대학원을 졸업 후 2013년 JNC 음악학원을 설립하였습니다. 12년간 수백 명의 학생을 지도하며 목동 지역 음악교육의 선두를 이끌고 있습니다.',
    subjects: ['플루트', '관현악 기초 이론'],
  },
  {
    id: 'jo-guk-hwa',
    name: '조국화',
    instrument: '피아노',
    icon: '🎹',
    part: '피아노',
    education: ['음악대학 피아노과 졸업'],
    career: ['JNC 음악학원 피아노 강사', '클래식 피아노 전공 지도'],
    bio: '클래식 피아노를 전공한 경력 강사로, 유아부터 입시생까지 체계적인 커리큘럼으로 지도합니다.',
    subjects: ['피아노 클래식', '피아노 입시'],
  },
  {
    id: 'kim-so-hyeong',
    name: '김소형',
    instrument: '피아노',
    icon: '🎹',
    part: '피아노',
    education: ['음악대학 피아노과 졸업'],
    career: ['JNC 음악학원 피아노 강사', '피아노 앙상블 지도'],
    bio: '피아노 전공 강사로 학생 개개인의 수준에 맞는 맞춤형 레슨을 제공합니다.',
    subjects: ['피아노 클래식', '피아노 취미'],
  },
  {
    id: 'choi-ji-yeong',
    name: '최지영',
    instrument: '피아노',
    icon: '🎹',
    part: '피아노',
    education: ['음악대학 피아노과 졸업'],
    career: ['JNC 음악학원 피아노 강사', '취미반 · 성인반 지도'],
    bio: '피아노 전공 강사로 취미반부터 입시반까지 폭넓게 지도합니다.',
    subjects: ['피아노 클래식', '피아노 취미', '성인반'],
  },
  {
    id: 'kim-malg-eum',
    name: '김맑음',
    instrument: '오보에',
    icon: '🎵',
    part: '관현악',
    education: ['음악대학 관악과 오보에 전공 졸업'],
    career: ['JNC 음악학원 오보에 강사', '오케스트라 단원 활동'],
    bio: '오보에 전공 강사로 기초부터 전공 입시까지 전문적으로 지도합니다.',
    subjects: ['오보에'],
  },
  {
    id: 'yi-yun-seok',
    name: '이윤석',
    instrument: '베이스',
    icon: '🎸',
    part: '실용음악',
    education: ['실용음악과 베이스 전공 졸업'],
    career: ['JNC 음악학원 베이스 강사', '세션 뮤지션 활동'],
    bio: '베이스 기타 전문 강사로 실용음악 입시 및 취미 연주까지 다양한 수준의 학생을 지도합니다.',
    subjects: ['베이스 기타', '실용음악 이론'],
  },
  {
    id: 'nam-seon-o',
    name: '남선오',
    instrument: '베이스',
    icon: '🎸',
    part: '실용음악',
    education: ['실용음악과 베이스 전공 졸업'],
    career: ['JNC 음악학원 베이스 강사', '밴드 활동 및 공연 경력'],
    bio: '베이스 기타 강사로 즉흥 연주와 이론을 균형 있게 가르칩니다.',
    subjects: ['베이스 기타', '밴드 합주'],
  },
  {
    id: 'mun-se-yeong',
    name: '문세영',
    instrument: '보컬',
    icon: '🎤',
    part: '성악',
    education: ['실용음악과 보컬 전공 졸업'],
    career: ['JNC 음악학원 보컬 강사', '뮤지컬 · 팝 보컬 전문'],
    bio: '보컬 전문 강사로 발성 교정부터 무대 퍼포먼스까지 종합적인 보컬 교육을 제공합니다.',
    subjects: ['팝 보컬', '뮤지컬', '발성 교정'],
  },
  {
    id: 'gwon-si-mun',
    name: '권시문',
    instrument: '드럼',
    icon: '🥁',
    part: '실용음악',
    education: ['실용음악과 드럼 전공 졸업'],
    career: ['JNC 음악학원 드럼 강사', '라이브 공연 드럼 세션'],
    bio: '드럼 전공 강사로 다양한 장르의 리듬을 체계적으로 지도합니다.',
    subjects: ['드럼', '퍼커션'],
  },
  {
    id: 'cheon-ga-hui',
    name: '천가희',
    instrument: '드럼',
    icon: '🥁',
    part: '실용음악',
    education: ['실용음악과 드럼 전공 졸업'],
    career: ['JNC 음악학원 드럼 강사', '앙상블 · 밴드 합주 지도'],
    bio: '드럼 강사로 초보자도 쉽게 따라올 수 있는 단계별 커리큘럼을 운영합니다.',
    subjects: ['드럼', '밴드 합주'],
  },
  {
    id: 'tae-yu-min',
    name: '태유민',
    instrument: '드럼',
    icon: '🥁',
    part: '실용음악',
    education: ['실용음악과 드럼 전공 졸업'],
    career: ['JNC 음악학원 드럼 강사', '세션 드러머 활동'],
    bio: '드럼 전공 강사로 팝·록·재즈 등 다양한 장르 드럼을 지도합니다.',
    subjects: ['드럼', '실용음악 입시'],
  },
  {
    id: 'kim-yeo-bin',
    name: '김여빈',
    instrument: '기타',
    icon: '🎸',
    part: '실용음악',
    education: ['실용음악과 기타 전공 졸업'],
    career: ['JNC 음악학원 기타 강사', '기타 솔로 · 앙상블 활동'],
    bio: '기타 전공 강사로 입문자부터 입시생까지 체계적인 기타 교육을 제공합니다.',
    subjects: ['기타', '코드 · 솔로잉'],
  },
  {
    id: 'yi-sang-hyeon',
    name: '이상현',
    instrument: '기타',
    icon: '🎸',
    part: '실용음악',
    education: ['실용음악과 기타 전공 졸업'],
    career: ['JNC 음악학원 기타 강사', '작편곡 · 세션 기타리스트'],
    bio: '기타 및 작편곡 강사로 기타 연주와 더불어 음악 이론을 폭넓게 지도합니다.',
    subjects: ['기타', '작편곡'],
  },
  {
    id: 'gong-seong-yun',
    name: '공성윤',
    instrument: '기타',
    icon: '🎸',
    part: '실용음악',
    education: ['실용음악과 기타 전공 졸업'],
    career: ['JNC 음악학원 기타 강사', '라이브 공연 활동'],
    bio: '기타 강사로 클래식 기타부터 일렉기타까지 다양한 스타일을 가르칩니다.',
    subjects: ['기타', '어쿠스틱 · 일렉기타'],
  },
  {
    id: 'han-su-jeong',
    name: '한수정',
    instrument: '트럼펫',
    icon: '🎺',
    part: '관현악',
    education: ['음악대학 관악과 트럼펫 전공 졸업'],
    career: ['JNC 음악학원 트럼펫 강사', '오케스트라 · 앙상블 활동'],
    bio: '트럼펫 전공 강사로 기초 주법부터 전공 입시까지 전문 지도합니다.',
    subjects: ['트럼펫', '브라스 앙상블'],
  },
];
